### ISSUE TITLE
[SUGGESTION] Inheritance

### ISSUE THREAD

**Issue by Gayytis** [Nononitas/Plugin-Hide-Pro#2]
**Is your feature request related to a problem? Please describe.**

It's really anoying to add every new command to each group, something like a tree permission could be a cool feature. I explain myself :

I'd like something like groupmanager's inheritance feature. The commands in tab-complete category from the default group could be added to the "group2" and the new command of the group2, to the "group3"

Without having to add every new command to each group

**Comment by Nononitas** [comment]
This feature already exist:
In the "included-groups" section you can add other groups (The group type of the inherited groups is that of the parent group). The commands and tab completion from the "included groups" will be added to this group. Note that the implemented groups don't implement their implemented groups!​
